#!/usr/bin/env bash
# Copyright 2026 Scalytics, Inc.
# Copyright 2026 Mirko Kämpf
#
# Generate SPEC/FR/INDEX.md from all req-*.md files.
# Usage: hack/req-index.sh [--check]

set -euo pipefail

CHECK="${1:-}"
INDEX_FILE="SPEC/FR/INDEX.md"
REQ_DIR="SPEC/FR"

if [ ! -d "$REQ_DIR" ]; then
    echo "ERROR: $REQ_DIR directory not found"
    exit 1
fi

# Generate index content
CONTENT="# Requirements Index

*Auto-generated by \`hack/req-index.sh\` — do not edit manually.*

| ID | Title | Status | Phase | Priority |
|----|-------|--------|-------|----------|
"

for f in "$REQ_DIR"/req-*.md; do
    [ -f "$f" ] || continue
    BASENAME=$(basename "$f" .md)
    ID=$(echo "$BASENAME" | sed 's/req-/REQ-/')

    TITLE=$(head -1 "$f" | sed 's/^# REQ-[0-9]*: //')
    STATUS=$(grep -m1 '^\*\*Status\*\*:' "$f" | sed 's/\*\*Status\*\*: //' || echo "Unknown")
    PHASE=$(grep -m1 '^\*\*Phase\*\*:' "$f" | sed 's/\*\*Phase\*\*: //' || echo "-")
    PRIORITY=$(grep -m1 '^\*\*Priority\*\*:' "$f" | sed 's/\*\*Priority\*\*: //' || echo "-")

    CONTENT+="| $ID | $TITLE | $STATUS | $PHASE | $PRIORITY |
"
done

CONTENT+="
---

*Generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')*
"

if [ "$CHECK" = "--check" ]; then
    if [ -f "$INDEX_FILE" ]; then
        # Compare without the timestamp line
        EXISTING=$(head -n -3 "$INDEX_FILE")
        GENERATED=$(echo "$CONTENT" | head -n -3)
        if [ "$EXISTING" = "$GENERATED" ]; then
            echo "PASS: $INDEX_FILE is up to date."
            exit 0
        fi
    fi
    echo "FAIL: $INDEX_FILE is out of date. Run 'make req-index' to regenerate."
    exit 1
fi

echo "$CONTENT" > "$INDEX_FILE"
echo "Generated $INDEX_FILE"
