source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-include-cache", "~> 0.2"
gem "rake", "~> 13.0"
